#!/bin/sh
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.

relation-set host=`facter couchdb_hostname` ip=`facter couchdb_ip`  port=`facter couchdb_port`
echo $ENSEMBLE_REMOTE_UNIT joined
