#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot


apt-get -y install python-software-properties debconf debconf-utils
apt-add-repository ppa:facter-plugins/ppa
apt-get -y update
apt-get install -y couchdb facter facter-customfacts-plugin uuid python-couchdb pwgen

DEFAULT_ADMIN_PASSWORD=`pwgen -N1`
DEFAULT_REPLICATION_PASSWORD=`pwgen -N1`

fact-add couchdb_hostname `facter fqdn`
fact-add couchdb_ip `facter ipaddress`
fact-add couchdb_port 5984
fact-add couchdb_replication ${DEFAULT_REPLICATION_PASSWORD}
fact-add couchdb_admin ${DEFAULT_ADMIN_PASSWORD}

sed -i.bak -e "s/bind_address =.*/bind_address = `facter couchdb_ip`/" /etc/couchdb/default.ini
sed -i.bak -e "s/;port =.*/port = `facter couchdb_port`/" \
           -e "s/;bind_address.*/bind_address = `facter couchdb_ip`/" \
           -e "s/; require_valid_user = false/require_valid_user = true/" \
           -e "s/;admin =.*/admin = ${DEFAULT_ADMIN_PASSWORD}/" \
           /etc/couchdb/local.ini

echo "replication = ${DEFAULT_REPLICATION_PASSWORD}" >> /etc/couchdb/local.ini

service couchdb status && service couchdb restart || service couchdb start

[ -x `which open-port` ] && open-port `facter couchdb-port`/TCP
